use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use kb_core::{
    BuildRecord, Citation, EntityMetadata, NormalizedDocument, Status, hash_many,
    rewrite_managed_region,
};
use kb_llm::{LlmAdapter, LlmAdapterError, ProvenanceRecord, SummarizeDocumentRequest};

const SUMMARY_REGION_ID: &str = "summary";

/// Output emitted by the source summary pass for one normalized document.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceSummaryArtifact {
    /// Concise prose summary generated by the LLM.
    pub summary: String,
    /// Key headings/topics carried forward for lexical indexing.
    pub key_headings: Vec<String>,
    /// Revision-level citations supporting the generated summary section.
    pub citations: Vec<Citation>,
    /// Managed region content to insert into the source page.
    pub managed_region_content: String,
    /// Full source page body after upserting the managed summary region.
    pub page_body: String,
    /// Build metadata for this pass execution.
    pub build_record: BuildRecord,
}

/// Errors produced by the source summary pass.
#[derive(Debug, thiserror::Error)]
pub enum SourceSummaryError {
    #[error("llm summarize_document failed: {0}")]
    Llm(#[from] LlmAdapterError),
    #[error("failed to read system time: {0}")]
    Time(String),
}

/// Generate a source summary artifact for a normalized document.
///
/// The pass delegates prose summary generation to `LlmAdapter::summarize_document`,
/// derives key headings from the normalized document heading IDs, emits revision-level
/// citations, and prepares managed-region markdown for the source wiki page.
///
/// # Errors
///
/// Returns [`SourceSummaryError`] when the LLM adapter fails or when system time cannot
/// be converted into the build record timestamp.
pub fn run_source_summary_pass<A: LlmAdapter>(
    adapter: &A,
    document: &NormalizedDocument,
    title: &str,
    max_words: usize,
    source_page_id: &str,
    source_page_path: impl AsRef<Path>,
    existing_page_body: Option<&str>,
) -> Result<SourceSummaryArtifact, SourceSummaryError> {
    let source_page_path = source_page_path.as_ref().to_path_buf();
    let request = SummarizeDocumentRequest {
        title: title.to_string(),
        body: document.canonical_text.clone(),
        max_words,
    };

    let (response, provenance) = adapter.summarize_document(request)?;
    let key_headings = document.heading_ids.clone();
    let citations = build_citations(document, &key_headings);
    let managed_region_content = render_managed_region_content(&response.summary, &key_headings);
    let page_body = upsert_source_summary_region(existing_page_body.unwrap_or(""), &managed_region_content);
    let build_record = build_record_for_summary(
        document,
        &source_page_path,
        source_page_id,
        &response.summary,
        &key_headings,
        &provenance,
    )?;

    Ok(SourceSummaryArtifact {
        summary: response.summary,
        key_headings,
        citations,
        managed_region_content,
        page_body,
        build_record,
    })
}

fn build_citations(document: &NormalizedDocument, key_headings: &[String]) -> Vec<Citation> {
    if key_headings.is_empty() {
        return vec![Citation {
            metadata: citation_metadata(&document.source_revision_id, None),
            source_revision_id: document.source_revision_id.clone(),
            claim_text: None,
            heading_anchor: None,
            line_span: None,
            char_span: None,
            page_number: None,
            asset_ref: None,
        }];
    }

    key_headings
        .iter()
        .map(|heading| Citation {
            metadata: citation_metadata(&document.source_revision_id, Some(heading)),
            source_revision_id: document.source_revision_id.clone(),
            claim_text: None,
            heading_anchor: Some(heading.clone()),
            line_span: None,
            char_span: None,
            page_number: None,
            asset_ref: None,
        })
        .collect()
}

fn citation_metadata(source_revision_id: &str, heading_anchor: Option<&str>) -> EntityMetadata {
    let anchor_suffix = heading_anchor
        .map(|anchor| format!("#{anchor}"))
        .unwrap_or_default();
    EntityMetadata {
        id: format!("citation:{source_revision_id}{anchor_suffix}"),
        ..EntityMetadata::default()
    }
}

fn render_managed_region_content(summary: &str, key_headings: &[String]) -> String {
    let mut content = String::new();
    content.push('\n');
    content.push_str(summary.trim());
    content.push('\n');

    if !key_headings.is_empty() {
        content.push_str("\n### Key headings\n");
        for heading in key_headings {
            content.push_str("- `");
            content.push_str(heading);
            content.push_str("`\n");
        }
    }

    content
}

/// Upsert the `summary` managed region inside a source wiki page body.
#[must_use]
pub fn upsert_source_summary_region(page_body: &str, managed_region_content: &str) -> String {
    if let Some(updated) = rewrite_managed_region(page_body, SUMMARY_REGION_ID, managed_region_content)
    {
        return updated;
    }

    let mut rendered = page_body.trim_end().to_string();
    if !rendered.is_empty() {
        rendered.push_str("\n\n");
    }
    rendered.push_str("## Summary\n");
    rendered.push_str("<!-- kb:begin id=summary -->");
    rendered.push_str(managed_region_content);
    rendered.push_str("<!-- kb:end id=summary -->\n");
    rendered
}

fn build_record_for_summary(
    document: &NormalizedDocument,
    source_page_path: &Path,
    source_page_id: &str,
    summary: &str,
    key_headings: &[String],
    provenance: &ProvenanceRecord,
) -> Result<BuildRecord, SourceSummaryError> {
    let now = unix_time_ms()?;
    let prompt_template_hash = provenance.prompt_template_hash.to_hex();
    let prompt_render_hash = provenance.prompt_render_hash.to_hex();
    let headings_joined = key_headings.join("\n");
    let manifest_hash = hash_many(&[
        document.metadata.id.as_bytes(),
        b"\0",
        document.source_revision_id.as_bytes(),
        b"\0",
        summary.as_bytes(),
        b"\0",
        headings_joined.as_bytes(),
        b"\0",
        prompt_render_hash.as_bytes(),
    ])
    .to_hex();

    Ok(BuildRecord {
        pass_name: "source_summary".to_string(),
        metadata: EntityMetadata {
            id: format!("build:source-summary:{}", document.metadata.id),
            created_at_millis: now,
            updated_at_millis: now,
            source_hashes: vec![
                document.metadata.id.clone(),
                document.source_revision_id.clone(),
                prompt_render_hash,
            ],
            model_version: Some(provenance.model.clone()),
            tool_version: Some(format!("{}/{}", env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION"))),
            prompt_template_hash: Some(prompt_template_hash),
            dependencies: vec![document.metadata.id.clone(), document.source_revision_id.clone()],
            output_paths: vec![source_page_path.to_path_buf()],
            status: Status::Fresh,
        },
        input_ids: vec![document.metadata.id.clone(), document.source_revision_id.clone()],
        output_ids: vec![source_page_id.to_string()],
        manifest_hash,
        pass_name: "source_summary".to_string(),
    })
}

fn unix_time_ms() -> Result<u64, SourceSummaryError> {
    let duration = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|err| SourceSummaryError::Time(err.to_string()))?;
    let millis = duration
        .as_millis()
        .try_into()
        .context("system time exceeded u64 millisecond range")
        .map_err(|err| SourceSummaryError::Time(err.to_string()))?;
    Ok(millis)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    use kb_core::{EntityMetadata, Hash, Status};
    use kb_llm::{
        LlmAdapter, LlmAdapterError, ProvenanceRecord, SummarizeDocumentResponse, TokenUsage,
    };

    #[derive(Debug)]
    struct FakeAdapter {
        response: String,
        provenance: ProvenanceRecord,
        expected_title: String,
        expected_body: String,
        expected_max_words: usize,
    }

    impl LlmAdapter for FakeAdapter {
        fn summarize_document(
            &self,
            request: SummarizeDocumentRequest,
        ) -> Result<(SummarizeDocumentResponse, ProvenanceRecord), LlmAdapterError> {
            assert_eq!(request.title, self.expected_title);
            assert_eq!(request.body, self.expected_body);
            assert_eq!(request.max_words, self.expected_max_words);
            Ok((
                SummarizeDocumentResponse {
                    summary: self.response.clone(),
                },
                self.provenance.clone(),
            ))
        }

        fn extract_concepts(
            &self,
            _request: kb_llm::ExtractConceptsRequest,
        ) -> Result<(kb_llm::ExtractConceptsResponse, ProvenanceRecord), LlmAdapterError> {
            unreachable!("unused in source summary test")
        }

        fn merge_concept_candidates(
            &self,
            _request: kb_llm::MergeConceptCandidatesRequest,
        ) -> Result<(kb_llm::MergeConceptCandidatesResponse, ProvenanceRecord), LlmAdapterError> {
            unreachable!("unused in source summary test")
        }

        fn answer_question(
            &self,
            _request: kb_llm::AnswerQuestionRequest,
        ) -> Result<(kb_llm::AnswerQuestionResponse, ProvenanceRecord), LlmAdapterError> {
            unreachable!("unused in source summary test")
        }

        fn generate_slides(
            &self,
            _request: kb_llm::GenerateSlidesRequest,
        ) -> Result<(kb_llm::GenerateSlidesResponse, ProvenanceRecord), LlmAdapterError> {
            unreachable!("unused in source summary test")
        }

        fn run_health_check(
            &self,
            _request: kb_llm::RunHealthCheckRequest,
        ) -> Result<(kb_llm::RunHealthCheckResponse, ProvenanceRecord), LlmAdapterError> {
            unreachable!("unused in source summary test")
        }
    }

    fn normalized_document() -> NormalizedDocument {
        NormalizedDocument {
            metadata: EntityMetadata {
                id: "normalized-doc-1".to_string(),
                created_at_millis: 1,
                updated_at_millis: 1,
                source_hashes: vec!["source-hash-1".to_string()],
                model_version: None,
                tool_version: None,
                prompt_template_hash: None,
                dependencies: vec![],
                output_paths: vec![],
                status: Status::Fresh,
            },
            source_revision_id: "source-revision-1".to_string(),
            canonical_text: "# Title\n\nBody text here.\n".to_string(),
            normalized_assets: vec![],
            heading_ids: vec!["title".to_string(), "details".to_string()],
        }
    }

    fn provenance() -> ProvenanceRecord {
        ProvenanceRecord {
            harness: "opencode".to_string(),
            harness_version: None,
            model: "openai/gpt-5.4".to_string(),
            prompt_template_name: "summarize_document.md".to_string(),
            prompt_template_hash: Hash::from([2u8; 32]),
            prompt_render_hash: Hash::from([3u8; 32]),
            started_at: 10,
            ended_at: 20,
            latency_ms: 10,
            retries: 0,
            tokens: Some(TokenUsage {
                prompt_tokens: 42,
                completion_tokens: 12,
            }),
            cost_estimate: None,
        }
    }

    #[test]
    fn source_summary_pass_emits_summary_citations_and_build_record() {
        let document = normalized_document();
        let adapter = FakeAdapter {
            response: "A concise source summary.".to_string(),
            provenance: provenance(),
            expected_title: "Example Source".to_string(),
            expected_body: document.canonical_text.clone(),
            expected_max_words: 80,
        };

        let artifact = run_source_summary_pass(
            &adapter,
            &document,
            "Example Source",
            80,
            "wiki-page-1",
            Path::new("wiki/sources/example-source.md"),
            None,
        )
        .expect("run source summary pass");

        assert_eq!(artifact.summary, "A concise source summary.");
        assert_eq!(artifact.key_headings, vec!["title", "details"]);
        assert_eq!(artifact.citations.len(), 2);
        assert_eq!(artifact.citations[0].source_revision_id, "source-revision-1");
        assert_eq!(artifact.citations[0].heading_anchor.as_deref(), Some("title"));
        assert!(artifact.page_body.contains("<!-- kb:begin id=summary -->"));
        assert!(artifact.page_body.contains("A concise source summary."));
        assert!(artifact.page_body.contains("### Key headings"));
        assert_eq!(artifact.build_record.pass_name, "source_summary");
        assert_eq!(artifact.build_record.metadata.model_version.as_deref(), Some("openai/gpt-5.4"));
        let expected_prompt_hash = Hash::from([2u8; 32]).to_hex();
        assert_eq!(
            artifact.build_record.metadata.prompt_template_hash.as_deref(),
            Some(expected_prompt_hash.as_str())
        );
        assert_eq!(artifact.build_record.output_ids, vec!["wiki-page-1"]);
        assert_eq!(
            artifact.build_record.metadata.output_paths,
            vec![PathBuf::from("wiki/sources/example-source.md")]
        );
    }

    #[test]
    fn upsert_source_summary_region_rewrites_existing_region_only() {
        let original = "# Source\n\n<!-- kb:begin id=summary -->\nOld summary.\n<!-- kb:end id=summary -->\n\n## Notes\nKeep me.\n";
        let updated = upsert_source_summary_region(original, "\nNew summary.\n");

        assert!(updated.contains("New summary."));
        assert!(updated.contains("## Notes\nKeep me."));
        assert!(!updated.contains("Old summary."));
    }
}
